---
- name: Install nginx
  yum:
    name: nginx
    state: present

- name: Copy nginx config file
  copy:
    src: etc/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart nginx

- name: Be sure nginx enabled and started
  service:
    name: nginx
    enabled: yes
    state: started
